### ISSUE TITLE
overflow issue

### ISSUE THREAD

**Issue by dailycommit** [wearethescenery/ether#2]
Looks like there's a minor bug on the https://ether.thescenery.co/

``top: -100px;`` is not working properly with ``width: 100vw;``

```css
/* main.css */

body:before {
    background-color: #083138;
    bottom: 0;
    content: "";
    left: 0;
    opacity: 0;
    position: absolute;
    top: -100px;
    visibility: hidden;
    width: 100vw;
    z-index: 100;
}
```

macOS Sierra v10.12.4  / Chrome Version 63.0.3239.108 (Official Build) (64-bit)

<img width="1438" alt="overflow-issue" src="https://user-images.githubusercontent.com/31360927/34298101-06fc95be-e72d-11e7-9f82-2229c6f6f868.png">
